version: "3.9"

services:
  headhuntermonitoringbot:
    container_name: headhuntermonitoringbot
    image: headhuntermonitoringbot:1.0
    restart: unless-stopped
    network_mode: host

    volumes:
      # Внешняя папка для SQLite БД
      - /usr/projects/hh-monitor/data:/app/data

      # Локальное время сервера
      - /etc/localtime:/etc/localtime:ro

      - /usr/projects/hh_monitor/config:/config

    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      # TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      # TELEGRAM_USERNAME: ${TELEGRAM_USERNAME}